import './globals.css'
import type { Metadata } from 'next'

import { DM_Sans } from 'next/font/google'
import SideBar from './(component)/Navbar'

const dmSans=DM_Sans({
subsets:['latin'],
display:'swap',
variable:'--font-dm-sans'
})


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <SideBar/>
      <body className={dmSans.className}>{children}</body>
    </html>
  )
}
